services:
  gsag-calypso:
    build: .
    image: gsag-calypso
    environment:
      MONGODB_DOMAIN: "mongodb"
    restart: "unless-stopped"
    networks:
      - gsag-calypso
    depends_on:
      - mongodb

  gsag-calypso-api:
    build: api
    image: gsag-calypso-api
    environment:
      MONGODB_DOMAIN: "mongodb"
    ports:
      - 4145:80
    restart: "unless-stopped"
    networks:
      - gsag-calypso
    depends_on:
      - mongodb

  mongodb:
    image: mongo:6-jammy
    ports:
      - "127.0.0.1:27017:27017"
    expose:
      - 27017
    volumes:
      - ./db:/data/db
    networks:
      - gsag-calypso

networks:
  gsag-calypso:
